language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

sudo: false

env:
  - CXX=g++-5

script:
  - cp config.sample.js config.js
  - jshint src/
  - npm test

notifications:
  email: false

after_success:
  - npm run coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

